[package]
name = "rust-tone"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
cast = "0.2"
cursive = "0.8"
failure = "0.1"
libpulse-binding = "1.2"
libpulse-simple-binding = "1.2"
